from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel


class ApplicationBase(BaseModel):
    # Matches the real Supabase "applications" table (confirmed via
    # information_schema.columns + pg_constraint audit, Sept 2026).
    # FK: applicant_id -> applicants(id) ON DELETE CASCADE.
    # FK: reviewed_by -> users(id). No FK to "leads" exists on this table.
    applicant_id: UUID
    application_no: Optional[str] = None
    # DB default '2026-27'; left optional so create() can omit it and let
    # the database default apply.
    academic_year: Optional[str] = None
    # DB CHECK constraint applications_programme_check restricts this to
    # B.E. / B.Tech / M.E. / M.Tech / MBA / MCA. Left as free text so a
    # constraint violation surfaces as a clear 400 from Supabase rather
    # than being silently reshaped by the API.
    programme: str
    department: str
    branch: Optional[str] = None
    preferred_hostel: Optional[bool] = None
    preferred_transport: Optional[bool] = None
    transport_route: Optional[str] = None
    # DB default 'Draft'
    application_stage: Optional[str] = None
    merit_rank: Optional[int] = None
    # DB CHECK constraint applications_allotted_seat_type_check restricts
    # this to Management / Government / NRI / Lateral Entry / Spot.
    allotted_seat_type: Optional[str] = None
    remarks: Optional[str] = None
    submitted_at: Optional[datetime] = None
    reviewed_by: Optional[UUID] = None
    reviewed_at: Optional[datetime] = None
    category: Optional[str] = None


class ApplicationCreate(ApplicationBase):
    pass


class ApplicationResponse(ApplicationBase):
    id: UUID
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class ApplicationUpdate(BaseModel):
    """PATCH model — every field optional. application_no is deliberately
    excluded: generated by a BEFORE INSERT trigger (generate_application_no()),
    and triggers don't fire on UPDATE, so exposing it here would let a
    client silently overwrite the generated, sequence-backed value."""
    applicant_id: Optional[UUID] = None
    academic_year: Optional[str] = None
    programme: Optional[str] = None
    department: Optional[str] = None
    branch: Optional[str] = None
    preferred_hostel: Optional[bool] = None
    preferred_transport: Optional[bool] = None
    transport_route: Optional[str] = None
    application_stage: Optional[str] = None
    merit_rank: Optional[int] = None
    allotted_seat_type: Optional[str] = None
    remarks: Optional[str] = None
    submitted_at: Optional[datetime] = None
    reviewed_by: Optional[UUID] = None
    reviewed_at: Optional[datetime] = None
    category: Optional[str] = None
