from datetime import date, datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel


class ApplicantBase(BaseModel):
    # Matches the real Supabase "applicants" table (confirmed via Table Editor,
    # column-by-column, Sept 2026). Note: this table has several redundant/legacy
    # columns from the original Streamlit CRM (e.g. both date_of_birth and dob,
    # both phone and mobile, both first_name/last_name and full_name, both
    # address_line1/2 and address, both twelfth_school and school_name). These
    # are kept exactly as-is per the audit-first rule — not cleaned up here.
    # reg_number is server-generated (two BEFORE INSERT triggers,
    # set_reg_number/trg_reg_number, both call a reg-number generator) and
    # is UNIQUE — left optional/omittable on create, present on response.
    reg_number: Optional[str] = None
    first_name: str
    last_name: str
    date_of_birth: Optional[date] = None
    gender: Optional[str] = None
    phone: str
    alternate_phone: Optional[str] = None
    email: Optional[str] = None
    address_line1: Optional[str] = None
    address_line2: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    pincode: Optional[str] = None
    aadhaar_number: Optional[str] = None
    category: Optional[str] = None
    community_cert_no: Optional[str] = None
    twelfth_school: Optional[str] = None
    twelfth_board: Optional[str] = None
    twelfth_year: Optional[int] = None
    twelfth_percentage: Optional[float] = None
    twelfth_group: Optional[str] = None
    pcm_marks: Optional[float] = None
    cutoff_marks: Optional[float] = None
    entrance_exam: Optional[str] = None
    entrance_rank: Optional[int] = None
    entrance_score: Optional[float] = None
    parent_name: Optional[str] = None
    parent_phone: Optional[str] = None
    parent_occupation: Optional[str] = None
    annual_income: Optional[float] = None
    lead_source: Optional[str] = None
    referred_by: Optional[str] = None
    assigned_counselor: Optional[UUID] = None
    status: Optional[str] = None
    # DB CHECK constraint: applicants_priority_check restricts this to
    # High / Normal / Low (default 'Normal'). Left as free text here so a
    # constraint violation surfaces as a clear 400 from Supabase rather
    # than being silently reshaped by the API.
    priority: Optional[str] = None
    notes: Optional[str] = None
    created_by: Optional[UUID] = None
    blood_group: Optional[str] = None
    father_name: Optional[str] = None
    mother_name: Optional[str] = None
    father_mobile: Optional[str] = None
    address: Optional[str] = None
    school_name: Optional[str] = None
    hsc_percentage: Optional[float] = None
    reference_name: Optional[str] = None
    programme_interested: Optional[str] = None
    department_interested: Optional[str] = None
    doc_status: Optional[dict[str, Any]] = None
    full_name: Optional[str] = None
    mobile: Optional[str] = None
    dob: Optional[date] = None


class ApplicantCreate(ApplicantBase):
    pass


class ApplicantResponse(ApplicantBase):
    id: UUID
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class ApplicantUpdate(BaseModel):
    """PATCH model — every field optional. reg_number is deliberately
    excluded: it's generated by a BEFORE INSERT trigger, and triggers
    don't fire on UPDATE, so exposing it here would let a client silently
    overwrite the generated, format-guaranteed value. created_by is also
    excluded: it is set once at creation time from the authenticated
    caller (app/services/applicants_service.create_applicant) and must
    stay a reliable audit record, not something a later PATCH can
    rewrite."""
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    date_of_birth: Optional[date] = None
    gender: Optional[str] = None
    phone: Optional[str] = None
    alternate_phone: Optional[str] = None
    email: Optional[str] = None
    address_line1: Optional[str] = None
    address_line2: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    pincode: Optional[str] = None
    aadhaar_number: Optional[str] = None
    category: Optional[str] = None
    community_cert_no: Optional[str] = None
    twelfth_school: Optional[str] = None
    twelfth_board: Optional[str] = None
    twelfth_year: Optional[int] = None
    twelfth_percentage: Optional[float] = None
    twelfth_group: Optional[str] = None
    pcm_marks: Optional[float] = None
    cutoff_marks: Optional[float] = None
    entrance_exam: Optional[str] = None
    entrance_rank: Optional[int] = None
    entrance_score: Optional[float] = None
    parent_name: Optional[str] = None
    parent_phone: Optional[str] = None
    parent_occupation: Optional[str] = None
    annual_income: Optional[float] = None
    lead_source: Optional[str] = None
    referred_by: Optional[str] = None
    assigned_counselor: Optional[UUID] = None
    status: Optional[str] = None
    priority: Optional[str] = None
    notes: Optional[str] = None
    blood_group: Optional[str] = None
    father_name: Optional[str] = None
    mother_name: Optional[str] = None
    father_mobile: Optional[str] = None
    address: Optional[str] = None
    school_name: Optional[str] = None
    hsc_percentage: Optional[float] = None
    reference_name: Optional[str] = None
    programme_interested: Optional[str] = None
    department_interested: Optional[str] = None
    doc_status: Optional[dict[str, Any]] = None
    full_name: Optional[str] = None
    mobile: Optional[str] = None
    dob: Optional[date] = None
